TaxesPrivatBank/ViewModels/TaxesViewModel.cs
using System;

namespace TaxesPrivatBank.ViewModels
{
    /// <summary>
    /// The taxes view model.
    /// </summary>
    public class TaxesViewModel
    {
        /// <summary>
        /// Gets or sets the credits.
        /// </summary>
        public Statement[] Statements { get; set; }

        /// <summary>
        /// Gets or sets the full amount.
        /// </summary>
        public double FullAmount { get; set; }

        /// <summary>
        /// Gets or sets the date start.
        /// </summary>
        public DateTime StartDate { get; set; }

        /// <summary>
        /// Gets or sets the date end.
        /// </summary>
        public DateTime EndDate { get; set; }

        /// <summary>
        /// Gets or sets the taxes amount.
        /// </summary>
        public double TaxesAmount { get; set; }

        /// <summary>
        /// Gets or sets the interest rate.
        /// </summary>
        public double InterestRate { get; set; }

        /// <summary>
        /// The credit view model.
        /// </summary>
        public class Statement
        {
            /// <summary>
            /// Gets or sets the amount.
            /// </summary>
            public double Amount { get; set; }

            /// <summary>
            /// Gets or sets the amount in uah.
            /// </summary>
            public double AmountInUAH { get; set; }

            /// <summary>
            /// Gets or sets the description.
            /// </summary>
            public string Description { get; set; }

            /// <summary>
            /// Gets or sets a value indicating whether this instance is taxed.
            /// </summary>
            public bool IsTaxed { get; set; }

            /// <summary>
            /// Gets or sets the CCY.
            /// </summary>
            public string CCY { get; set; }

            /// <summary>
            /// Gets or sets the date.
            /// </summary>
            public DateTime Date { get; set; }

            /// <summary>
            /// Gets or sets the currency exchange.
            /// </summary>
            public double CurrencyExchange { get; set; }
        }
    }
}

TaxesPrivatBank/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaxesprivatBank.Core.Dto;
using TaxesPrivatBank.Business;
using TaxesPrivatBank.Business.Interfaces;
using TaxesPrivatBank.Helpers;

namespace TaxesPrivatBank.Controllers
{
    /// <summary>
    /// The account controller.
    /// </summary>
    public class AccountController : Controller
    {

        /// <summary>
        /// The privat bank manager
        /// </summary>
        private IPrivatBankManager privatBankManager;

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountController"/> class.
        /// </summary>
        public AccountController()
        {
            this.privatBankManager = new PrivatBankManager();
        }

        // GET: Account
        public ActionResult LoginToPB()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LoginToPB(string login, string password)
        {
            ActionResult result = null;
            PBSessionDto session = this.privatBankManager.GetSession();
            PBPersonSessionDto personSession = this.privatBankManager
                .GetPersonSession(session.ID, login, password);
            CookieHelper.PBSessionID = personSession.ID;
            if (personSession.Message.StartsWith("Authentication successful"))
            {
                result = this.RedirectToAction("Index", "Home", null);
            }
            else
            {
                result = this.RedirectToAction("ConfirmCode", "Account");
            }

            return result;
        }

        public ActionResult ConfirmCode()
        {
            return this.View();
        }

        [HttpPost]
        public ActionResult ConfirmCode(string code)
        {
            string sessionID = CookieHelper.PBSessionID;
            PBPersonSessionDto personSession = this.privatBankManager.ConfirmSmsCode(sessionID, code);
            CookieHelper.PBSessionID = personSession.ID;
            return this.RedirectToAction("Index", "Home", null);
        }
    }
}

TaxesPrivatBank/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TaxesPrivatBank.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }



        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TaxesPrivatBank/Controllers/TaxesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TaxesPrivatBank.Business;
using TaxesPrivatBank.Business.Interfaces;
using TaxesPrivatBank.Helpers;
using TaxesPrivatBank.ViewModels;

namespace TaxesPrivatBank.Controllers
{
    /// <summary>
    /// The taxes controller.
    /// </summary>
    public class TaxesController : Controller
    {
        /// <summary>
        /// The privat bank manager.
        /// </summary>
        private IPrivatBankManager privatBankManager;

        /// <summary>
        /// Initializes a new instance of the <see cref="TaxesController"/> class.
        /// </summary>
        public TaxesController()
        {
            this.privatBankManager = new PrivatBankManager();
        }

        /// <summary>
        /// The generate taxes page.
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            TaxesViewModel model = new TaxesViewModel();

            string sessionID = CookieHelper.PBSessionID;
            var taxes = this.privatBankManager
                .GetTaxes(sessionID, DateTime.Parse("04.01.2016"), DateTime.Parse("06.30.2016"), 5);

            model.FullAmount = taxes.FullAmount;
            model.StartDate = taxes.StartDate;
            model.EndDate = taxes.EndDate;
            model.TaxesAmount = taxes.TaxesAmount;
            model.InterestRate = taxes.InterestRate;

            List<TaxesViewModel.Statement> credits = new List<TaxesViewModel.Statement>();
            foreach (var statement in taxes.Statements)
            {
                credits.Add(new TaxesViewModel.Statement()
                {
                    Amount = statement.Amount.Amount,
                    Description = statement.Purpose,
                    IsTaxed = statement.IsTaxed,
                    CCY = statement.Amount.CCY,
                    Date = statement.Info.PostDate,
                    CurrencyExchange = statement.Course,
                    AmountInUAH = statement.AmountInUAH,
                });
            }

            model.Statements = credits.ToArray();

            return View(model);
        }
    }
}

TaxesPrivatBank/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TaxesPrivatBank/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TaxesPrivatBank/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Главная";
}

<div class="jumbotron">
    <h1>Налоги в Приват24 для бизнеса</h1>
    <p class="lead">Налоги в Приват24 для бизнеса - это удобное Веб приложение для подсчета единого налога за определенный период.</p>
    <a href="@Url.Action("LoginToPB", "Account")" class="btn btn-success">Залогиниться в Приват24 еу</a>
</div>

TaxesPrivatBank/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Налоги в Приват24", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Главная", "Index", "Home")</li>
                    <li>@Html.ActionLink("Рассчитать налог", "Index", "Taxes")</li>
                    <li>@Html.ActionLink("О приложении", "About", "Home")</li>
                    <li>@Html.ActionLink("Контакты", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TaxesPrivatBank/Views/Taxes/Index.cshtml
@model TaxesPrivatBank.ViewModels.TaxesViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Доходы предприятия</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                Дата
            </th>
            <th>
                Облагается налогом
            </th>
            <th>
                Описание дохода
            </th>
            <th>
                Сума дохода
            </th>
            <th>
                Валюта
            </th>
            <th>
                Курс
            </th>
            <td>
                Сума в гривнах
            </td>
        </tr>
    </thead>
    <tbody>
        @foreach(var statement in Model.Statements)
        {
            <tr>
                <td>
                    @statement.Date.ToString("dd.MM.yyyy")
                </td>
                <td>
                    @statement.IsTaxed
                </td>
                <td>
                    @statement.Description
                </td>
                <td>
                    @statement.Amount
                </td>
                <td>
                    @statement.CCY
                </td>
                <td>
                    @statement.CurrencyExchange
                </td>
                <td>
                    @statement.AmountInUAH
                </td>
            </tr>
        }
    </tbody>
</table>

<h2>Общая сумма дохода с @Model.StartDate.ToString("dd.MM.yyyy") по @Model.EndDate.ToString("dd.MM.yyyy") составляет @Model.FullAmount.ToString("F")</h2>
<h2>Надо отдать в налоговую @Model.TaxesAmount.ToString("F") грн по ставке @Model.InterestRate%</h2>